name: Run ansible

on:
  push:
    paths:
      - .github/workflows/ansible.yaml
  workflow_dispatch:

jobs:
  run_ansible:
    runs-on: ubuntu-latest
    steps:
      - run: ansible --version
      - run: ansible localhost -m ping
