name: Check available executables in runner

on: workflow_dispatch

jobs:
  check_avail_execs:
    runs-on: ubuntu-latest
    steps:
      - name: List available executables
        run: |
          echo $PATH | tr ':' '\n' | while read -r dir; do 
            [ "$(ls -A "$dir")" ] && ls "$dir"; 
          done  | xargs -L1 | sort | uniq
