on:
  workflow_dispatch:

name: Failing workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build app
      run: echo Building...  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Deploy app
      run: echo Deploying app... && exit 1
  run_python_if_prev_job_failed:
    needs: [deploy]
    if: ${{ failure() }}
    uses: gkochyli/github-actions-playground/.github/workflows/run-python.yaml@main
  app-tests:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - name: Running app tests
      run: echo Running app tests
      


