on:
  workflow_dispatch:

name: Failing workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build app
      run: echo Building...  
  deploy:
    outputs:
      server_error: ${{ steps.deployment.outputs.server_error }}
      app_error: ${{ steps.deployment.outputs.app_error }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Deploy app
      id: deployment
      run: |
        echo Deploying app...
        >&2 echo "error" && echo "server_error=1" >> "$GITHUB_OUTPUT"
        exit 1
  python_fix_server_errors:
    needs: [deploy]
    if: ${{ failure() && needs.deploy.outputs.server_error == 1 }}
    uses: gkochyli/github-actions-playground/.github/workflows/run-python.yaml@feat/failing_workflow
  python_fix_app_errors:
    needs: [deploy]
    if: ${{ failure() && needs.deploy.outputs.app_error == 1 }}
    uses: gkochyli/github-actions-playground/.github/workflows/run-python.yaml@feat/failing_workflow
  app-tests:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - name: Running app tests
      run: echo Running app tests
      


