on:
  workflow_dispatch:

name: Failing workflow

jobs:
  build:
    steps:
    - name: Build app
      run: echo Building...  
  deploy:
    needs: [build]
    steps:
    - name: Deploy app
      run: echo Deploying app... && exit 1
  run_python_if_prev_job_failed:
    needs: [deploy]
    if: ${{ failure() }}
    steps:
    - uses: actions/checkout@v4
    - uses: .github/workflows/run-python.yaml@main
  app-tests:
    needs: [deploy]
    steps:
    - name: Running app tests
      run: echo Running app tests
      


