name: example

on:
  push: 
    branches: [ "main" ]
    paths: [ ".github/workflows/init-exaple.yaml" ]
  workflow_dispatch:
  
jobs:
  init-example:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, World
      - name: Run a multi-line script
        run: |
          echo First line
          echo Second line
