name: example

on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  oneline-script:
    runs-on: alpine-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, World
