name: Job with dynamic variable matrix

on:
  push:
    paths: [.github/workflows/job_with_dynamic_var_matrix.yml]
jobs:
  create_matrix_var:
    outputs:
      ARRAY: ${{ steps.step1.outputs.ARRAY }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          export ARRAY="[1, 2, 3]"
          echo "ARRAY=$ARRAY" >> "$GITHUB_OUTPUT"
          env | grep TEST
        id: step1
  use_vars:
    runs-on: ubuntu-latest
    needs: create_matrix_var
    env:
      array: ${{needs.create_matrix_var.outputs.ARRAY}}
    strategy:
      matrix:
        item: $ARRAY
    steps:
      - name: Echoing ${{ matrix.item }}
        run: |
          echo ${{ matrix.item }}
          env | grep TEST
