name: Job with dynamic variable matrix

on:
  push:
    paths: [.github/workflows/job_with_dynamic_var_matrix.yml]
jobs:
  create_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"tags\":\"foo\"},{\"tags\":\"bar\"},{\"tags\":\"zzz\"}]}" >> $GITHUB_OUTPUT
  run_from_var_matrix:
    needs: create_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.create_matrix.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.tags }}
