name: Job with dynamic matrix

on:
  push:
    paths: [.github/workflows/job_with_dynamic_matrix.yml]
jobs:
  pass_vars:
    outputs:
      TEST: ${{ steps.step1.outputs.TEST }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          export TEST=2
          echo "TEST=$TEST" >> "$GITHUB_OUTPUT"
          env | grep TEST
        id: step1
  use_vars:
    runs-on: ubuntu-latest
    needs: pass_vars
    steps:
      - run: |
          echo ${{ needs.pass_vars.outputs.TEST }}
          env | grep TEST
