name: "Multiple jobs, write/read from file"

on:
  push:
    paths:
      - .github/workflows/multiple_jobs_read_write_to_file.yaml
  workflow_dispatch:
  
jobs:
  write_to_file:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, World
      - name: Write to file
        run: echo bar > foo
      - name: Cat file foo
        run: cat foo
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: foo-file
          path: foo
  read_from_file:
    runs-on: ubuntu-latest
    needs: write_to_file
    steps:
      - name: Run a multi-line script
        run: |
          echo First line \
          Second line
      - name: Download foo-file from artifacts
        uses: actions/download-artifact@v3
        with:
          name: foo-file
      - name: Cat foo from first job
        run: cat foo