name: Use secrets between jobs

on:
  push:
    paths: [ ".github/workflows/secrets_in_jobs.yaml" ]
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      secret: ${{ steps.output1.outputs.SECRET }}
    steps:
      - id: output1
        run: echo "SECRET=${{secrets.SECRETS_IN_JOBS}}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Output secret from job1
        run: echo ${{ needs.job1.outputs.secret }}
