name: Use secrets between jobs

on:
  push:
    paths: [ ".github/workflows/secrets_in_jobs.yaml" ]
  workflow_dispatch:

# When outputs contain secret values the runner does not allow the use of the output.
# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     outputs:
#       secret: ${{ steps.output1.outputs.SECRET }}
#     steps:
#       - id: output1
#         run: echo "SECRET=${{secrets.SECRETS_IN_JOBS}}" >> "$GITHUB_OUTPUT"
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - name: Output secret from job1
#         run: echo ${{ needs.job1.outputs.secret }}

# 2nd try
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      secret: ${{ steps.output1.outputs.SECRET }}
    steps:
      - id: output1
        run: |
          ENCODED_SECRET=$(echo ${{secrets.SECRETS_IN_JOBS}}|base64)
          echo "SECRET=$ENCODED_SECRET" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Output secret from job1
        run: echo ${{ needs.job1.outputs.secret }} | base64 -d
