name: Vars between steps

on:
  push:
    paths: [.github/workflows/vars_between_steps.yml]
jobs:
  pass_vars:
    runs-on: ubuntu-latest
    env:
      TEST: ''
    steps:
      - run: export TEST='test1'
      - run: echo $TEST
      
