name: Vars between jobs

on:
  push:
    paths: [.github/workflows/vars_between_jobs.yml]
jobs:
  pass_vars:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export TEST=test1
          echo "TEST=$TEST" >> "$GITHUB_OUTPUT"
          env | grep TEST
  use_vars:
    runs-on: ubuntu-latest
    needs: pass_vars
    steps:
      - run: |
          echo ${{ needs.pass_vars.outputs.TEST }}
          env | grep TEST
      
